import type { DiscoveryResult } from "./mockDiscovery";

const EXPORT_FILENAME = "product-discovery-output.md";

function formatListSection(title: string, items: string[]): string {
  const lines = items.map((item) => `- ${item}`);
  return `## ${title}\n\n${lines.join("\n")}\n`;
}

export function buildDiscoveryMarkdown(
  productIdea: string,
  businessGoal: string,
  results: DiscoveryResult,
): string {
  const exportedAt = new Date().toISOString();
  const goalText = businessGoal.trim() || "_Not provided._";

  return [
    "# Product Discovery Output",
    "",
    "_Generated by AI Product Discovery Agent_",
    "",
    `**Exported:** ${exportedAt}`,
    "",
    "## Product Idea",
    "",
    productIdea.trim(),
    "",
    "## Business Goal",
    "",
    goalText,
    "",
    formatListSection("Discovery Questions", results.discoveryQuestions),
    formatListSection("Business Requirements", results.businessRequirements),
    formatListSection("User Stories", results.userStories),
    formatListSection("MVP Scope", results.mvpScope),
    formatListSection("Scope Risks", results.scopeRisks),
    formatListSection("What Not To Build Yet", results.whatNotToBuild),
  ].join("\n");
}

export function downloadDiscoveryMarkdown(
  productIdea: string,
  businessGoal: string,
  results: DiscoveryResult,
): void {
  const markdown = buildDiscoveryMarkdown(productIdea, businessGoal, results);
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = EXPORT_FILENAME;
  link.rel = "noopener";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export { EXPORT_FILENAME };
